version: '3.8'

services:
  php:
    build: .
    container_name: online-dj-booking-management-system-php
    ports:
      - "8081:80"
    volumes:
      - ./odms:/var/www/html
    networks:
      - app-network
    environment:
      # Sử dụng tên service thay vì IP
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=odmsdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: online-dj-booking-management-system-mysql
    environment:
      # Không đặt password cho root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: odmsdb
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL File/odmsdb.sql:/docker-entrypoint-initdb.d/odmsdb.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: